metrics_enabled: false
debug: true
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - io.dropwizard
    - com.hello

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    sense_sensors_data : dev_sense_sensors_data

app_name: SenseLastSeen
max_records: 100
trim_horizon: false

logging:
  level: INFO
  loggers:
    com.hello.suripu.workers: DEBUG
    com.hello.suripu.core: DEBUG
  appenders:
    - type: file
      threshold: DEBUG
      currentLogFilename: /var/log/suripu-workers/suripu-workers-sense-lastseen.log
      archivedLogFilenamePattern: /var/log/suripu-workers/suripu-workers-sense-lastseen-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: suripu-workers-sense-lastseen-dev
      # timezone: UTC
      # facility: USER
      # sendLocalName: true

dynamodb:
  region: us-east-1
  tables:
    features: features
    wifi_info: wifi_info
    sense_last_seen: sense_last_seen

  endpoints:
    features: http://dynamodb.us-east-1.amazonaws.com
    wifi_info: http://dynamodb.us-east-1.amazonaws.com
    sense_last_seen: http://dynamodb.us-east-1.amazonaws.com

