metrics_enabled: true
debug: false
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - io.dropwizard
    - com.hello

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    sense_sensors_data : sense_sensors_data

app_name: SenseLastSeenProd
max_records: 200
trim_horizon: false

logging:
  level: INFO
  loggers:
    com.hello.suripu.workers: INFO
  appenders:
    - type: file
      threshold: DEBUG
      currentLogFilename: /var/log/suripu-workers/suripu-workers-sense-lastseen.log
      archivedLogFilenamePattern: /var/log/suripu-workers/suripu-workers-sense-lastseen-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: suripu-workers-sense-lastseen-prod
      # timezone: UTC
      # facility: USER
      # sendLocalName: true

dynamodb:
  region: us-east-1
  default_endpoint: http://dynamodb.us-east-1.amazonaws.com
  tables:
    features: features
    wifi_info: prod_wifi_info
    sense_last_seen: prod_sense_last_seen
  endpoints: {}

