metrics_enabled: false
debug: true
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 15
  include_metrics:
    - io.dropwizard
    - com.hello

common_db:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver
  user: ingress_user
  password: hello ingress user
  url: jdbc:postgresql://chanku-test.cdawj8qazvva.us-east-1.rds.amazonaws.com:5432/chanku

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"

  initialSize: 2

  # the minimum number of connections to keep open
  minSize: 2

  # the maximum number of connections to keep open
  maxSize: 2

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
    push_notifications: dev_push_notifications

app_name: PushNotificationsConsumer

max_records: 100

# Logging settings.
logging:
  level: INFO
  loggers:
    com.hello.suripu.workers: DEBUG
  appenders:
    - type: file
      threshold: DEBUG
      currentLogFilename: /var/log/suripu-workers/suripu-workers-push.log
      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      archivedLogFilenamePattern: /var/log/suripu-workers/suripu-workers-push-%d{yyyy-MM-dd}.log.gz
      # The number of archived files to keep.
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: suripu-workers-push-dev
      # timezone: UTC
      # facility: USER
      # sendLocalName: true

dynamodb:
  region: us-east-1
  tables:
    alarm_info: prod_alarm_info
    app_stats: app_stats
    features: features
    preferences: prod_preferences
    push_notification_event: push_notification_event
    timezone_history: timezone_history
  endpoints:
    alarm_info: http://dynamodb.us-east-1.amazonaws.com
    app_stats: http://dynamodb.us-east-1.amazonaws.com
    features : http://dynamodb.us-east-1.amazonaws.com
    preferences: http://dynamodb.us-east-1.amazonaws.com
    push_notification_event: http://dynamodb.us-east-1.amazonaws.com
    timezone_history: http://dynamodb.us-east-1.amazonaws.com

push_notifications:
  arns:
    ios: arn:aws:sns:us-east-1:053216739513:app/APNS/hello-sense-ios-dev
    android: arn:aws:sns:us-east-1:053216739513:app/GCM/hello-sense-android-dev

  table_name: notifications

active_hours:
  - 18
  - 19
  - 20

