debug: true
metrics_enabled: false
graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - io.dropwizard
    - com.hello

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  streams :
      sense_sensors_data : dev_sense_sensors_data

app_name: AlarmWorker

max_records: 1000

maximum_record_age_minutes: 15

# Logging settings.
logging:
  level: INFO
  loggers:
    com.hello.suripu.workers: INFO
  appenders:
    - type: file
      threshold: DEBUG
      currentLogFilename: /var/log/suripu-workers/suripu-workers-alarm.log
      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      archivedLogFilenamePattern: /var/log/suripu-workers/suripu-workers-alarm-%d{yyyy-MM-dd}.log.gz
      # The number of archived files to keep.
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: suripu-workers-alarm-dev
      # timezone: UTC
      # facility: USER
      # sendLocalName: true

dynamodb:
  region: us-east-1
  default_endpoint: http://dynamodb.us-east-1.amazonaws.com
  tables:
    alarm_info: alarm_info
    features: features
    pill_data: pill_data
    ring_time: ring_time
    smart_alarm_log: smart_alarm_log
    timezone_history: timezone_history
  endpoints: {}

aggregate_window_size_min: 15

smart_alarm_process_ahead_in_minutes: 30

light_sleep_init_threshold: 0.2
